export const FETCH_PLAYERS_START = "FETCH_PLAYERS_START";
export const FETCH_PLAYERS_SUCCESS = "FETCH_PLAYERS_SUCCESS";
export const FETCH_PLAYERS_FAIL = "FETCH_PLAYERS_FAIL";
 
export const DELETE_PLAYERS_START = "DELETE_PLAYERS_START";
export const DELETE_PLAYERS_SUCCESS = "DELETE_PLAYERS_SUCCESS";
export const DELETE_PLAYERS_FAIL = "DELETE_PLAYERS_FAIL";

export const FETCH_HOME_START = "FETCH_HOME_START";
export const FETCH_HOME_SUCCESS = "FETCH_HOME_SUCCESS";
export const FETCH_HOME_FAIL = "FETCH_HOME_FAIL";
